# Generated by Django 4.1.1 on 2022-11-22 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="faculty", name="f_email",),
        migrations.RemoveField(model_name="faculty", name="f_fname",),
        migrations.RemoveField(model_name="myadmin", name="ad_email",),
        migrations.RemoveField(model_name="myadmin", name="ad_fname",),
        migrations.RemoveField(model_name="student", name="s_email",),
        migrations.RemoveField(model_name="student", name="s_fname",),
    ]
