# Generated by Django 4.1.1 on 2022-11-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "eduficationapp",
            "0002_remove_faculty_f_email_remove_faculty_f_fname_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Program",
            fields=[
                ("p_id", models.AutoField(primary_key=True, serialize=False)),
                ("p_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("c_id", models.AutoField(primary_key=True, serialize=False)),
                ("c_name", models.CharField(max_length=50)),
                (
                    "c_programid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.program",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Batch",
            fields=[
                ("b_id", models.AutoField(primary_key=True, serialize=False)),
                ("b_name", models.CharField(max_length=50)),
                (
                    "b_programid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.program",
                    ),
                ),
            ],
        ),
    ]
