# Generated by Django 4.1.1 on 2022-11-26 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0003_program_course_batch"),
    ]

    operations = [
        migrations.RemoveField(model_name="student", name="s_statusid",),
    ]
