# Generated by Django 4.1.1 on 2022-11-26 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0004_remove_student_s_statusid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="s_batchid",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="student",
            name="s_parentscontact",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
