# Generated by Django 4.1.1 on 2022-11-26 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0005_alter_student_s_batchid_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bcf",
            fields=[
                ("bcf_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "bcf_batchid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.batch",
                    ),
                ),
                (
                    "bcf_courseid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.course",
                    ),
                ),
                (
                    "bcf_facultyid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
