# Generated by Django 4.1.1 on 2022-11-28 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0006_bcf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="s_batchid",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="eduficationapp.batch",
            ),
        ),
    ]
