# Generated by Django 4.1.1 on 2022-11-30 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0007_alter_student_s_batchid"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="s_status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                max_length=200,
                null=True,
            ),
        ),
    ]
