# Generated by Django 4.1.1 on 2022-12-10 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0009_faculty_f_status_alter_student_s_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faculty",
            name="f_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="myadmin",
            name="ad_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
        migrations.AlterField(
            model_name="student",
            name="s_image",
            field=models.ImageField(
                blank=True, default="images/default.jpg", null=True, upload_to="images/"
            ),
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                ("l_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "l_name",
                    models.CharField(
                        choices=[
                            ("Announcement", "Announcement"),
                            ("Lecture", "Lecture"),
                        ],
                        max_length=255,
                    ),
                ),
                ("l_desc", models.CharField(max_length=1000)),
                (
                    "l_file",
                    models.FileField(blank=True, null=True, upload_to="lectures/"),
                ),
                (
                    "l_bcfid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.bcf",
                    ),
                ),
            ],
        ),
    ]
