# Generated by Django 4.1.1 on 2022-12-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "eduficationapp",
            "0010_alter_faculty_f_image_alter_myadmin_ad_image_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                ("a_id", models.AutoField(primary_key=True, serialize=False)),
                ("a_name", models.CharField(max_length=255)),
                ("a_desc", models.CharField(max_length=1000)),
                ("a_startdate", models.DateTimeField()),
                ("a_enddate", models.DateTimeField()),
                (
                    "a_file",
                    models.FileField(blank=True, null=True, upload_to="assignments/"),
                ),
                ("a_mark", models.IntegerField()),
                (
                    "a_bcfid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.bcf",
                    ),
                ),
            ],
        ),
    ]
