# Generated by Django 4.1.1 on 2022-12-16 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0011_assignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                ("q_id", models.AutoField(primary_key=True, serialize=False)),
                ("q_name", models.CharField(max_length=255)),
                ("q_startdate", models.DateTimeField()),
                ("q_enddate", models.DateTimeField()),
                ("q_question", models.IntegerField()),
                (
                    "q_bcfid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.bcf",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                ("qq_id", models.AutoField(primary_key=True, serialize=False)),
                ("qq_question", models.CharField(max_length=255)),
                ("qq_option1", models.CharField(max_length=255)),
                ("qq_option2", models.CharField(max_length=255)),
                ("qq_option3", models.CharField(max_length=255)),
                ("qq_option4", models.CharField(max_length=255)),
                ("qq_marks", models.IntegerField()),
                ("qq_correctanswer", models.CharField(max_length=255)),
                (
                    "qq_quizid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.quiz",
                    ),
                ),
            ],
        ),
    ]
