# Generated by Django 4.1.1 on 2023-02-07 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0013_attendance_attendancerecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssignmentSubmit",
            fields=[
                ("as_id", models.AutoField(primary_key=True, serialize=False)),
                ("as_file", models.FileField(upload_to="submitassignments/")),
                ("as_date", models.DateTimeField()),
                ("as_marks", models.IntegerField()),
                (
                    "as_assignmentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.assignment",
                    ),
                ),
                (
                    "as_studentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
