# Generated by Django 4.1.1 on 2023-02-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0014_assignmentsubmit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assignmentsubmit",
            name="as_marks",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
