# Generated by Django 4.1.1 on 2023-02-10 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0015_alter_assignmentsubmit_as_marks"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuizSubmit",
            fields=[
                ("qs_id", models.AutoField(primary_key=True, serialize=False)),
                ("qs_answer", models.CharField(max_length=255)),
                ("qs_obtmarks", models.IntegerField()),
                ("qs_tmarks", models.IntegerField()),
                (
                    "qs_questionid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.quizquestion",
                    ),
                ),
                (
                    "qs_quizid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.quiz",
                    ),
                ),
                (
                    "qs_studentid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
