# Generated by Django 4.1.1 on 2023-02-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0016_quizsubmit"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsubmit",
            name="qs_date",
            field=models.DateTimeField(null=True),
        ),
    ]
