# Generated by Django 4.1.1 on 2023-03-25 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0018_bcf_bcf_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="forget_password_token",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="myadmin",
            name="forget_password_token",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="forget_password_token",
            field=models.CharField(default="", max_length=100),
        ),
    ]
