# Generated by Django 4.1.1 on 2023-04-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0019_faculty_forget_password_token_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlagiarismReport",
            fields=[
                ("pr_id", models.AutoField(primary_key=True, serialize=False)),
                ("pr_plagiarism", models.IntegerField()),
                (
                    "pr_asid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="eduficationapp.assignmentsubmit",
                    ),
                ),
            ],
        ),
    ]
