# Generated by Django 4.1.1 on 2023-04-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eduficationapp", "0020_plagiarismreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="assignmentsubmit",
            name="as_plagiarismpercent",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(name="PlagiarismReport",),
    ]
